import type { SpiritInfo, PersonalityDefinition, SoulPool, SpiritType } from '@/types';

// 五灵宠配置
export const SPIRITS: Record<string, SpiritInfo> = {
  wisdom: {
    type: 'wisdom',
    name: '智慧灵',
    title: '专注守护者',
    description: '守护你的思维空间，关注学习与认知的专注度',
    focusItems: ['书籍', '电脑', '工作区核心布局'],
    psychologicalMapping: ['思维过载情况', '近期学习与认知专注度'],
    languageStyle: '理性沉稳、善用比喻',
    color: '#6366F1',
    emoji: '📚',
    iconLarge: '/spirits/wisdom.png',
    iconSmall: '/spirits/wisdom-sm.png',
  },
  vitality: {
    type: 'vitality',
    name: '活力灵',
    title: '行动守护者',
    description: '守护你的行动能量，关注执行力与任务冲刺',
    focusItems: ['ToDo便签', '项目材料', '杂乱工具'],
    psychologicalMapping: ['拖延症现状', '任务冲刺压力与行动能量'],
    languageStyle: '活泼直率、鼓励为主',
    color: '#F59E0B',
    emoji: '⚡',
    iconLarge: '/spirits/vitality.png',
    iconSmall: '/spirits/vitality-sm.png',
  },
  healing: {
    type: 'healing',
    name: '治愈灵',
    title: '情绪守护者',
    description: '守护你的情感空间，关注心理防线与自我疗愈',
    focusItems: ['收藏物', '照片', '情绪物件', '潮玩'],
    psychologicalMapping: ['心理防线', '情感寄托', '疲惫感与自我疗愈'],
    languageStyle: '温柔细腻、善解人意',
    color: '#EC4899',
    emoji: '🌸',
    iconLarge: '/spirits/healing.png',
    iconSmall: '/spirits/healing-sm.png',
  },
  fantasy: {
    type: 'fantasy',
    name: '奇想灵',
    title: '灵感守护者',
    description: '守护你的创意空间，关注灵感爆发与思维活跃度',
    focusItems: ['手办', '草稿纸', '灵感碎片散落'],
    psychologicalMapping: ['精神内耗或灵感爆发', '创意思维的活跃度'],
    languageStyle: '天马行空、脑洞大开',
    color: '#8B5CF6',
    emoji: '✨',
    iconLarge: '/spirits/fantasy.png',
    iconSmall: '/spirits/fantasy-sm.png',
  },
  guardian: {
    type: 'guardian',
    name: '守护灵',
    title: '生活守护者',
    description: '守护你的生活作息，关注安全感与健康信号',
    focusItems: ['药品', '水杯', '睡眠痕迹', '空投杂物'],
    psychologicalMapping: ['身体亚健康信号', '作息规律度', '基础安全感'],
    languageStyle: '关怀备至、细心周到',
    color: '#10B981',
    emoji: '🛡️',
    iconLarge: '/spirits/guardian.png',
    iconSmall: '/spirits/guardian-sm.png',
  },
};

export const SPIRIT_BEAST_NAMES: Record<SpiritType, string> = {
  guardian: '辟邪',
  vitality: '天禄',
  fantasy: '九尾狐',
  wisdom: '白泽',
  healing: '玄龟',
};

export function getSpiritBeastName(type: SpiritType): string {
  return SPIRIT_BEAST_NAMES[type];
}

// 主人格库（20个预设）
export const PERSONALITIES: PersonalityDefinition[] = [
  {
    id: 'arch_01',
    name: '执行派建筑师',
    tagline: '你的桌面不是混乱，是未命名的结构',
    description: '擅长在复杂系统中建立秩序，大脑里自带蓝图',
    triggerCondition: { wisdomMin: 80, vitalityMin: 70, logic: 'wisdom主导 + vitality辅助' },
    primarySpirit: 'wisdom',
    secondarySpirit: 'vitality',
  },
  {
    id: 'arch_02',
    name: '精密仪器师',
    tagline: '误差在你的世界里不配拥有姓名',
    description: '对细节的执着让你在混沌中保持精准',
    triggerCondition: { wisdomMin: 85, guardianMin: 65, logic: 'wisdom极高 + guardian支撑' },
    primarySpirit: 'wisdom',
    secondarySpirit: 'guardian',
  },
  {
    id: 'arch_03',
    name: '秩序织网者',
    tagline: '你把散落的一切编织成了网',
    description: '擅长连接碎片信息，在多线程中建立关联',
    triggerCondition: { wisdomMin: 75, fantasyMin: 70, logic: 'wisdom + fantasy双高' },
    primarySpirit: 'wisdom',
    secondarySpirit: 'fantasy',
  },
  {
    id: 'arch_04',
    name: '暗夜赶路人',
    tagline: '深夜的屏幕光是你最熟悉的日出',
    description: '在安静中持续前进，不张扬但从不停止',
    triggerCondition: { vitalityMin: 75, guardianMin: 70, healingMax: 50, logic: 'vitality高但healing低，暗示透支型努力' },
    primarySpirit: 'vitality',
    secondarySpirit: 'guardian',
  },
  {
    id: 'arch_05',
    name: '灵感闪电侠',
    tagline: '你的想法比手指更快',
    description: '创意爆发力极强，但容易在收尾阶段蒸发',
    triggerCondition: { fantasyMin: 85, vitalityMin: 65, wisdomMax: 60, logic: 'fantasy极高 + vitality辅助，wisdom偏低' },
    primarySpirit: 'fantasy',
    secondarySpirit: 'vitality',
  },
  {
    id: 'arch_06',
    name: '白日造梦者',
    tagline: '你在三次元搭建了二次元的避难所',
    description: '桌面是内心世界的投影，手办和摆件是你的精神锚点',
    triggerCondition: { fantasyMin: 80, healingMin: 70, logic: 'fantasy主导 + healing加持' },
    primarySpirit: 'fantasy',
    secondarySpirit: 'healing',
  },
  {
    id: 'arch_07',
    name: '静默守望者',
    tagline: '你不需要很多声音来证明自己的存在',
    description: '沉稳内敛，用行动而非言语守护自己的领地',
    triggerCondition: { guardianMin: 85, wisdomMin: 65, vitalityMax: 50, logic: 'guardian极高 + wisdom辅助，vitality偏低' },
    primarySpirit: 'guardian',
    secondarySpirit: 'wisdom',
  },
  {
    id: 'arch_08',
    name: '温柔结界师',
    tagline: '你在自己和世界之间画了一道柔光的边界',
    description: '善于营造舒适区，守护自己也照顾他人',
    triggerCondition: { guardianMin: 80, healingMin: 75, logic: 'guardian + healing双高' },
    primarySpirit: 'guardian',
    secondarySpirit: 'healing',
  },
  {
    id: 'arch_09',
    name: '能量修复师',
    tagline: '你是自己和他人的充电站',
    description: '疲惫时懂得停下，擅长在混乱中找到恢复节奏',
    triggerCondition: { healingMin: 85, guardianMin: 60, logic: 'healing极高' },
    primarySpirit: 'healing',
    secondarySpirit: 'guardian',
  },
  {
    id: 'arch_10',
    name: 'DDL前的超进化体',
    tagline: '截止线是你唯一的变身触发器',
    description: '平时看似随性，倒计时响起时战斗力指数级飙升',
    triggerCondition: { vitalityMin: 80, wisdomMin: 65, healingMax: 45, logic: 'vitality高 + healing极低，暗示压力驱动型' },
    primarySpirit: 'vitality',
    secondarySpirit: 'wisdom',
  },
  {
    id: 'arch_11',
    name: '碎片炼金术士',
    tagline: '你把时间的边角料炼成了金',
    description: '擅长在碎片化时间中挖掘价值，多任务并行是本能',
    triggerCondition: { vitalityMin: 75, fantasyMin: 70, wisdomMin: 65, logic: '三属性均衡偏高' },
    primarySpirit: 'vitality',
    secondarySpirit: 'fantasy',
  },
  {
    id: 'arch_12',
    name: '人间观察员',
    tagline: '你收集世界的细节，存入自己的灵感库',
    description: '敏锐的感知力让你捕捉到别人忽略的纹理',
    triggerCondition: { wisdomMin: 70, fantasyMin: 75, guardianMin: 60, logic: 'wisdom + fantasy双高 + guardian稳定' },
    primarySpirit: 'fantasy',
    secondarySpirit: 'wisdom',
  },
  {
    id: 'arch_13',
    name: '小宇宙主理人',
    tagline: '你的精神世界有完整的生态系统',
    description: '内心秩序清晰，自给自足，偶尔对外开放参观',
    triggerCondition: { guardianMin: 75, fantasyMin: 70, healingMin: 65, logic: 'guardian + fantasy + healing三高，内向丰富型' },
    primarySpirit: 'guardian',
    secondarySpirit: 'fantasy',
  },
  {
    id: 'arch_14',
    name: '彩虹收集者',
    tagline: '你在灰色日常里打捞出所有彩色碎片',
    description: '乐观是你的默认设置，治愈自己顺便照亮别人',
    triggerCondition: { healingMin: 80, fantasyMin: 70, vitalityMin: 60, logic: 'healing主导 + fantasy + vitality' },
    primarySpirit: 'healing',
    secondarySpirit: 'fantasy',
  },
  {
    id: 'arch_15',
    name: '解忧杂货店主',
    tagline: '你的存在本身就是一种安慰剂',
    description: '善于倾听和共情，总能在对的时间递出对的温柔',
    triggerCondition: { healingMin: 85, wisdomMin: 65, guardianMin: 60, logic: 'healing极高 + wisdom + guardian' },
    primarySpirit: 'healing',
    secondarySpirit: 'wisdom',
  },
  {
    id: 'arch_16',
    name: '逆流而上者',
    tagline: '你选择的方向，逆风也是顺风',
    description: '在压力中反而找到动力，越难越兴奋的稀有体质',
    triggerCondition: { vitalityMin: 85, guardianMin: 70, healingMax: 40, logic: 'vitality极高 + guardian支撑，低healing暗示抗压型' },
    primarySpirit: 'vitality',
    secondarySpirit: 'guardian',
  },
  {
    id: 'arch_17',
    name: '寂静风暴眼',
    tagline: '外面天翻地覆，你这里风平浪静',
    description: '拥有在混乱中心保持宁静的罕见定力',
    triggerCondition: { guardianMin: 85, healingMin: 70, vitalityMax: 45, logic: 'guardian极高 + healing，vitality低暗示静谧型' },
    primarySpirit: 'guardian',
    secondarySpirit: 'healing',
  },
  {
    id: 'arch_18',
    name: '五边形战士',
    tagline: '你没有短板，但这也意味着你需要选一个方向',
    description: '各方面均衡发展，正在寻找属于自己的侧重',
    triggerCondition: {
      wisdomMin: 60,
      vitalityMin: 60,
      healingMin: 60,
      fantasyMin: 60,
      guardianMin: 60,
      requiresLowVariance: true,
      logic: '五维全部及格且方差小于15',
    },
    primarySpirit: 'wisdom',
    secondarySpirit: 'vitality',
  },
  {
    id: 'arch_19',
    name: '旷野独行者',
    tagline: '你不需要路标，你自己就是方向',
    description: '独立性强，在无人区也能走出自己的轨迹',
    triggerCondition: { wisdomMin: 75, guardianMin: 75, fantasyMin: 65, healingMax: 45, logic: 'wisdom + guardian双高，低healing暗示独立型' },
    primarySpirit: 'wisdom',
    secondarySpirit: 'guardian',
  },
  {
    id: 'arch_20',
    name: '无限重启玩家',
    tagline: '你相信每个新开始都藏着上一次的存档',
    description: '善于从失败中快速恢复，每一次重启都带着经验值',
    triggerCondition: { vitalityMin: 75, healingMin: 70, fantasyMin: 65, logic: 'vitality + healing + fantasy三高，韧性型' },
    primarySpirit: 'vitality',
    secondarySpirit: 'healing',
  },
];

// 初始隐藏分池
export const INITIAL_SOUL_POOL: SoulPool = {
  wisdom: 0,
  vitality: 0,
  healing: 0,
  fantasy: 0,
  guardian: 0,
};

// 加载文案轮播
export const LOADING_MESSAGES = [
  '智慧灵正在整理空间线索...',
  '奇想灵正在搜集灵感碎片...',
  '守护灵正在感知桌面气息...',
  '正在建立灵居共鸣模型...',
  '正在寻找与你最契合的守护灵...',
];

// 16宫格区域定义
export const GRID_ZONES = [
  { row: 0, col: 0, name: '专注区', spirit: 'wisdom' },
  { row: 0, col: 1, name: '学习区', spirit: 'wisdom' },
  { row: 0, col: 2, name: '思考区', spirit: 'wisdom' },
  { row: 0, col: 3, name: '规划区', spirit: 'vitality' },
  { row: 1, col: 0, name: '工具区', spirit: 'vitality' },
  { row: 1, col: 1, name: '执行区', spirit: 'vitality' },
  { row: 1, col: 2, name: '创造区', spirit: 'fantasy' },
  { row: 1, col: 3, name: '灵感区', spirit: 'fantasy' },
  { row: 2, col: 0, name: '收藏区', spirit: 'healing' },
  { row: 2, col: 1, name: '情感区', spirit: 'healing' },
  { row: 2, col: 2, name: '休憩区', spirit: 'guardian' },
  { row: 2, col: 3, name: '生活区', spirit: 'guardian' },
  { row: 3, col: 0, name: '杂物区', spirit: 'guardian' },
  { row: 3, col: 1, name: '备用区', spirit: 'guardian' },
  { row: 3, col: 2, name: '扩展区', spirit: 'fantasy' },
  { row: 3, col: 3, name: '自由区', spirit: 'healing' },
];

// API配置
export const API_CONFIG = {
  qwen: {
    endpoint: import.meta.env.VITE_QWEN_API_ENDPOINT || 'https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation',
    apiKey: import.meta.env.VITE_QWEN_API_KEY || '',
  },
  deepseek: {
    endpoint: import.meta.env.VITE_DEEPSEEK_API_ENDPOINT || 'https://api.deepseek.com/v1/chat/completions',
    apiKey: import.meta.env.VITE_DEEPSEEK_API_KEY || '',
  },
};